all:
  children:
    raspberry_pi:
      hosts:
        hallon:
          ansible_host: 192.168.0.XXX  # Replace with your Pi's IP
          ansible_user: pi  # Or your Pi username
          ansible_python_interpreter: /usr/bin/python3
