apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 12h
  upgrade:
    remediation:
      retries: 5
  chart:
    spec:
      chart: keda
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
      interval: 12h
