apiVersion: v1
kind: Secret
metadata:
    name: hermes-workspace-gateway-key
    namespace: hermes-workspace
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:qtJcsB1DyB58uw7AK627l/84yTrHmmX+uLTVmnIReVxAAIAYKn6Q6a3/fW1wWzjDrXsPe8XFdJXIg7YDp/sQMw==,iv:YUI3DIUw2JKJGsbXM6LwUDqc3jD/hwpV0zeiG5OePDo=,tag:GD2oX3LZQuNiY4heJVUnTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBU1VOemlvRHJpdzAxbzVE
            NDFqT29RdUI5eTZNN2dVQmJsUGp6QURVdTI4CktPNEhRZVp2aDFMS05DRTlhd2xF
            V1ZoYWNWakc3S1FSdFJkbHJGUktWN2cKLS0tIFZrYlhRYVRMSEQ0K294dFd5dk9r
            K0xqZzhVdzVHei9pUVY1U3YzQTdOK3MKWESNkz6iRxIGnRoq2RUNpsGbV4u5kn2k
            cejpTyfuQyLX2olWI0NOn+SpVVtB73s4yk3kafYjLvp82FibsI54dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T18:51:21Z"
    mac: ENC[AES256_GCM,data:dV/m7BfFwqvVChWANQ+wFwwmAEpDG/U6Ylu6Wcb6/c3iUuoPJOPkCSE24Cs7C1QKNkdmu2NtNfg8SOEi6QVIN30/i36JHG5Ah+Cv6GSg1INIhAMcLiONoybWoi7gOG6LLjIo1frL+yT99qx2/6dNQJbKGH5Lsy3jiFKjJn2I/JU=,iv:iz1NMjpk4OyE8Uu3pklBAQ1LnstSTT963eBqFUons1o=,tag:BrRO99aEECkhwwiNMfplLw==,type:str]
    version: 3.13.2
