apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-workspace-data
  namespace: hermes-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: local-path
