apiVersion: v1
kind: Secret
metadata:
    name: hermes-workspace-auth
    namespace: hermes-workspace
stringData:
    HERMES_PASSWORD: ENC[AES256_GCM,data:wIWZw31/CvfBBBni79WOddel1LV/OMlKWDxHF8ed5MZ/MFCAPFbbo5mvXg8=,iv:J24tTND8KlTDE5rGSZBhNfBzsTkY2jImlNad5xdFGWA=,tag:gzkJWYgb7KGPZpXzOhfKsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWXpWTUpQM0RKUFl5bGd5
            NnQ1UFVRS2tRd29rbWJPRnU3Q3J1YkN5M1hFClZyaE82anMrUFZoVGtmeWZIL3BU
            Z09kV0RuYjNoY3NycTdtNXZ4ZXdTelUKLS0tIGJ1WXZDTG0rekFFVEFvVytORHRI
            R1luVklNR1J6WVNKbXlVcEpvRHFMQ1kKO8zDNitfRdOVuwIoVF6fxySvFOOAjx6m
            Bf0zXlurRGsActieucx8oRiR0YVwXTksh1cDH2f+84hdXJSLXRi+Rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T18:51:00Z"
    mac: ENC[AES256_GCM,data:QF9MN4rT00GjqJaSGwRNmHywCDfhu7XcFoVjW1A703zNZHvS6USyUAO7Kaq00x4TVbT5AHuPpk/dDO349xAbsROjQr+BUEyk5NPzD9nmEJ4RzplUeKi1z4GM7kTnMCNmhoyzaCUFyL0eFeqma3J6sK+ymL1XisHlzLOHpi5YDt4=,iv:s36ZIANVk1WYV06kYRpcrts1yqpoerVtc1qtxp86LLs=,tag:bvHNgngl0R6zXcvu7nH5hg==,type:str]
    version: 3.13.2
