apiVersion: v1
kind: Secret
metadata:
    name: hermes-workspace-auth
    namespace: hermes-workspace
stringData:
    HERMES_PASSWORD: ENC[AES256_GCM,data:wIWZw31/CvfBBBni79WOddel1LV/OMlKWDxHF8ed5MZ/MFCAPFbbo5mvXg8=,iv:J24tTND8KlTDE5rGSZBhNfBzsTkY2jImlNad5xdFGWA=,tag:gzkJWYgb7KGPZpXzOhfKsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a3RBYkJwUlBnMlVvM2pz
            bTNHU3p2ZkNVZC95WnhEUnpZTDF5RDJ0MW1VCi8rRE1FWjVCUUQ5WDNIdVVOVmln
            cjRWV2ZQN3Y0bi9TeVhENnVXRFphdUEKLS0tIGtrSGlkMVVSM1RQR08zWHdXTktq
            cTVoTUJsK2ZPeVNEOWpxa3BGQzhKbjAKaOaAEr7gaiOsKnc5kHOnhTbs+Ejejq6p
            5Q8hb19dvcbNVyxASH+PMlLlKigqplHTfJz8biJ4jVuxYzkxeJvh3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQThIQXNWd3QzSjFWMlg4
            OUlZcldrSGZ3NFJFZjg5ejhoQTNCenE5YTA4Cm1yQldreFZtNFc3S2l0LzFxOWpV
            OVFFYjBHaG1qaVBNQlhVa0ZvRmh3cFEKLS0tIGRWM2pGdFhVc3RYcEZVSmIrVjhk
            SElid1BXUENPaDRpTnNTaTcrZlBacDAKs6swf0xYFb/fpF1Ch/YA2IVH1DdbmaWt
            SCeKBWdBk3DxBemEPO3BToUoV213eVhY+mV9SLJpGPKqncL30BP1Mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T18:51:00Z"
    mac: ENC[AES256_GCM,data:QF9MN4rT00GjqJaSGwRNmHywCDfhu7XcFoVjW1A703zNZHvS6USyUAO7Kaq00x4TVbT5AHuPpk/dDO349xAbsROjQr+BUEyk5NPzD9nmEJ4RzplUeKi1z4GM7kTnMCNmhoyzaCUFyL0eFeqma3J6sK+ymL1XisHlzLOHpi5YDt4=,iv:s36ZIANVk1WYV06kYRpcrts1yqpoerVtc1qtxp86LLs=,tag:bvHNgngl0R6zXcvu7nH5hg==,type:str]
    version: 3.13.2
