apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
type: Opaque
# Create a Cloudflare API Token with Zone:DNS:Edit and Zone:Zone:Read permissions
# https://dash.cloudflare.com/profile/api-tokens
stringData:
  api-token: ENC[AES256_GCM,data:2eMeIY3dL7+cD7U+i2DeG+cGxjxOBF8qWBY2RN1XmlBO+Ypxdmijjg==,iv:IkQOOdb6oK5K0pM6gegQA8/ufiMb85e/1ErNYKo+ktQ=,tag:3LFqVn8F68dKsIZOgs2rqg==,type:str]
sops:
  age:
  - recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUUtlWm92R1FuZ3F5eUc5
      Wm1FYmd4MTJjb2svR1lmOFEzMkYvRG5ib0EwCnFGVlppemFKcVNGVXkrRzhjWlBC
      VTJCNGcwZ2RQNWo4K1BrMUIzak5wZ00KLS0tIFpCQVdjWlNKeU00ZXNWdFBCYlM5
      UkV4QTZWUHc1TjM2d1J2NzFrMGZDN0kK5/vw56Fk0pVFUURmRtc89+qh9/YGAila
      JFC5U6vDKAdo60G21JN0AekHjMqNs0NX3beoWnZ4b2d3LLqj+L+U+g==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T01:14:36Z"
  mac: ENC[AES256_GCM,data:57+G5u+PsRVIc6uapgp0ZQ/vFrgsyhGOkGofpeMMugkUz8iro1dXRHJg6XMIPcgwrWhXk3IDNfQYBuNBlANEFN2w00x3jPu/GP7Exj7yzewAZLnVJbbd/Ln8VxBRgHQrfgjzTnwDfNgJapAHc38SsB2xPRRCmeEv3KtflbAEzzI=,iv:khMEsbLx6VqQDHx/v63MObQ10lQSws3VhZkdg3Z40Ik=,tag:JY35StP5cx95cdUEUcw9JQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
