apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- arc-controller.yaml
- arc-cluster-runner.yaml
- flux-system-secrets.yaml
- metallb.yaml
- metallb-config.yaml
- external-dns.yaml
- cert-manager.yaml
- certificates.yaml
- traefik.yaml
- home-assistant.yaml
- pihole.yaml
- rustdesk.yaml
- renovate.yaml
- gatus.yaml
- keda.yaml
- keda-http.yaml
- mosquitto.yaml
- reloader.yaml
- grafana-alloy.yaml
- grafana-operator.yaml
- grafana-dashboards.yaml
- private-apps.yaml
- apps.yaml
