apiVersion: v1
kind: Secret
metadata:
    name: couchdb-credentials
    namespace: couchdb
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:gkz4Nd4=,iv:l4t4CQu1gm0uGQLUZaV31Q8QIhAX1EDhFm+oPdSI6t0=,tag:Ua+9dtTXCqZsgAXHCaNX8Q==,type:str]
    adminPassword: ENC[AES256_GCM,data:YlH5dK9oBvcIXp5imOp7ZlclGUunFS8YVlhfNy75W0TiWiQXLpLiqEnlwDJf0Lfd,iv:mLBbJzvbxjLglXJFsYLw23Wm0+Djt0SidwWoFTJz7sA=,tag:aeic1L/YDUoTalirAiDtrg==,type:str]
    cookieAuthSecret: ENC[AES256_GCM,data:3+qMW/PeMUjYud71uTIcqcND5oDN+g0BFNz//bSWConC6SrHTareGmT+BAzRssW6D5LsNG5mbepUPHD8M6W5cg==,iv:k7ISRRHSNV3b/2AEfqLCQ+MzK4Rw1q6TxWLGuxQNTWM=,tag:jQdvC2jF4S65p1fF3nQo7A==,type:str]
    erlangCookie: ENC[AES256_GCM,data:P+oPmn6CoxuQ68swnTjx+DXGEFEcRAJMw4c3pd/9RWzhycT9RQ4fg5bXHXZlpItlHWB9iLku9ht2CdCkTWC6rg==,iv:wOCtl0EDId8wfujqCRTAwoaxLRhEVQGI4paV3G2bg64=,tag:uDNm+V4nmfrFr+EFh4wy2g==,type:str]
    livesyncUsername: ENC[AES256_GCM,data:mt2Zy8n1XVk=,iv:VsfeYHrXWzt0SHVKBhH3w2+/i8142BAvKNaaCyMiS1o=,tag:y5WUDgAk7CISPuzfcMPP+A==,type:str]
    livesyncPassword: ENC[AES256_GCM,data:eVN6zwu/ipaKOLv61/nvD30fTyCwZAnZ9x8tb80td5IQvn5SjFXXdVcErovXjzD2,iv:Pf1XeTl0m/t0Lisq9OhfzutPMtLEKBpi6QEOOCzEbKU=,tag:uiTRAuKvljnJF5ey0tWHpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWnpFRGFLdEd6c3QwK0hX
            ZURxd2dndnNld2prc0NtR0xXeDFtMXBaM2lrCi9kbGh6bkZ0N1dwdUZNNHZkbzY4
            Skl0dDlzYVdiZFJ6ODBPaU1BbUlaZ1EKLS0tIENCNzlPcFd3OGVnVm9SRGtWbm1T
            ZnNnRnU1TXpNNlFMQk1xRUU0N3Q1b1kK3hDUYEQKCS9Q0SpR/CJulfB66eTW1BOU
            qCtxLQa+BgCcwIt+CzT4GUcwJXWXmlEPjsF4gnhzQU0CxG4IRytWXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T09:13:52Z"
    mac: ENC[AES256_GCM,data:Q0pdOW/GLxAdf5pMjXUe2X4r9DV2U9I9/V5b3+4OKCA7kN/5LK+vauGiG7HWzrOM2mjZhdCoS9rKSNEmlQzxA2/yXxWNaZ4I/6Cay+9uRhwE+r+NTzp2GfUMq0bBuyeIEtsKeVRg6sN+sTufvGTIq/jDtpwdaUmDfvk0PfwKPCk=,iv:2Fn+NeNXoOUrWLuRYhMgcrLAZNUXY4nj1QmziCKtJlM=,tag:XO7U+954qW+rWNphcDI6qA==,type:str]
    version: 3.13.3
