apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: alerts
  namespace: grafana-operator
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana-cloud
  title: Alerts
