apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 127.0.0.0/8

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    # MQTT Integration for Zigbee2MQTT
    mqtt:
      broker: mosquitto.mosquitto.svc.cluster.local
      port: 1883
      discovery: true
      discovery_prefix: homeassistant

    # Backups
    backup:
