apiVersion: v1
data:
    token: ENC[AES256_GCM,data:vuinH8N7ho9Uz1fn05qJysAqo/RkFXvGEqK4fApjxqFBb9Z2iPuVpWgIuRptDxtnlrk8c6+xrXpb4Fb3e1LYLuvNVo34buRPg5iapMk0nTjD0T8Jcg1UxnUN3IlpE8jynqKsrVJz8TfQXnLkieGEpHrZ4WfxOAO3fXXZrw==,iv:Xi5DTeFrRgkeJLJilcC1XDYixrBNuqvimSk3Tj0QNg8=,tag:RMow2IaCt0NwKTfLEoaisg==,type:str]
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQUxWNFNLUDNnS21leHF2
            SjliR3AvWUNxSFVIYlkxa2UyeEFqUmFkRzBVCmtsRnJuZDF1ZFVjck1saVR3WDFV
            cWl5UFFncndxbmZ3NTJxV245S3VMeEUKLS0tIDN2S1lEYjFweStwYjJJYWlLNXJ4
            SzdYeVZDQzJUUzFmQWpyN1M2Z0FYdE0KmLh9DABg4ucb/D1bNYjn0wGowH74IaFB
            Fh6+61THmoYuE/j07IjVokLHglCkVivKpju89Y4IEb/4U+Jdpxpcag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVitLRHdHTjhJYkMrTWoz
            VTE3d0taUTZxZ2w0SThYMDJOZFdFdnFuRWlRCnBRWWxYdUdPbGo1a0xlblArbUlo
            S2ZoU0JkN3hzblYyQUdxSnRORkdhYXMKLS0tIE1UdkVjNkJYQ29QK1R0ZUNoS0xl
            RUxpY1MvYkRPWnUybXNUYzRERjMxb00KP9rbDqLnxYU8lPEo+lAvOpNFuSVszmfJ
            Vh2UuK6xkuGjk7EJJB47UCwfIb9/9ConbcsGBI4Yh2dMFLwjkWmR9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-17T12:18:11Z"
    mac: ENC[AES256_GCM,data:ye1PwrQgBrs/VM78d3/9v6S9HwFcFKx816vU9lmYyzIM5D7epCIraImTBhjdk26TayW5h8lSUMZS5p4XrLWUIOJV9/SMm5mAGNdT0/+SwhtNUHh0g/mSgmmFxcWobF5Cit/PEY3pqJ7k8wtXaqge7glMkSAqLjLBfXBYjg+voFI=,iv:pgw2SW53jpz2IigmYyYz1cwfKp0QaJ8SI03X1sUIcBQ=,tag:SBSLh6PsUWVVK1Aiu8qsqw==,type:str]
    version: 3.11.0
