apiVersion: v1
data:
    token: ENC[AES256_GCM,data:vuinH8N7ho9Uz1fn05qJysAqo/RkFXvGEqK4fApjxqFBb9Z2iPuVpWgIuRptDxtnlrk8c6+xrXpb4Fb3e1LYLuvNVo34buRPg5iapMk0nTjD0T8Jcg1UxnUN3IlpE8jynqKsrVJz8TfQXnLkieGEpHrZ4WfxOAO3fXXZrw==,iv:Xi5DTeFrRgkeJLJilcC1XDYixrBNuqvimSk3Tj0QNg8=,tag:RMow2IaCt0NwKTfLEoaisg==,type:str]
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
sops:
    age:
        - recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbjUzMmdGS1hhVzd1aWwz
            RVNuWHd6Z0dpOXZzc2JDRnAwa2VVa2cyeGc0CmhDWG1HeWRTc0lFdWlwdGd5aW02
            WmVVUFlidWhYZ0FxLy9LeFFzZ0lBQjQKLS0tIFNBNzZJVHJBaUJLNVpLcVdrY0Fq
            MnVZdkRDVU1pUkpVb1NLS1F4eGZiMUEKGKnGezzuAxs4LpeWQtxeMve7aJy2cvJx
            YmRKoBuZC/uylat05jxgq3FEinxpFzCBCoVG19FCmsDoatLTorFIgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T12:18:11Z"
    mac: ENC[AES256_GCM,data:ye1PwrQgBrs/VM78d3/9v6S9HwFcFKx816vU9lmYyzIM5D7epCIraImTBhjdk26TayW5h8lSUMZS5p4XrLWUIOJV9/SMm5mAGNdT0/+SwhtNUHh0g/mSgmmFxcWobF5Cit/PEY3pqJ7k8wtXaqge7glMkSAqLjLBfXBYjg+voFI=,iv:pgw2SW53jpz2IigmYyYz1cwfKp0QaJ8SI03X1sUIcBQ=,tag:SBSLh6PsUWVVK1Aiu8qsqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
