apiVersion: v1
kind: Secret
metadata:
    name: ha-mcp-env
    namespace: ha-mcp
stringData:
    #ENC[AES256_GCM,data:RsssHCUFkQN+RzgxVTsRq+a86TV+Y901CX7kSWXDeEVfQfCy6sS0Mi6j48DC4naYP5NhHpzsWAksOjro8SzrAqI8PGhiEgk=,iv:QdGPj7kP5UbH7hhjjZ0muLZt/wPMS55TRq+B084kr/Q=,tag:moMf6EwXiWV9lbdpwBp3Gw==,type:comment]
    HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:9Q335Xs0COaF0p+QOp5j1nLcJ2naiQSw3LEz0XC3dXjyFMQpG66pRAAFM5CrgsuoVqM8/sXUPeB1jdhOcG5sV6iO0pGN0IofK8v/4O+PLwVglap8oSLNBQwjbgF+AvIrdD6bdpQEWC4oiCam3lHJmHl/LH+hU61F4codb19xcqivp6I5IS46MPs6DyppPD96kc9UB7l04KDb2f1vfuXogysSwvjlHngTsSuyG/884ac7uwBxtfA+,iv:0dTqn1//yuuMaAM0vGU8Qz3BKcG2GaGAsQzmowV03BI=,tag:ua96k5V1AYvIXFG0Hiao2w==,type:str]
    #ENC[AES256_GCM,data:tx4szyno+VEeaHUdnrMw0NXMo7FHE6Hf/aVSiGt04wEKiwc7nPTiijfhC+lMk/xpuUtLsZiyvlWVEPYdllGFvhaja4PZPjcx,iv:8Nf7NC0ZFoYzWoc4EOmcnn/mlkyct47T5qeGRZnMXLw=,tag:oZqHGAfPFONCEVtIWKenLA==,type:comment]
    #ENC[AES256_GCM,data:PxWkgs/bbDnAiykjVRHd2j41L42H98upt8GzqgPaXegUwBXL3/iN/oxO/CB+fhXpJcfBQIJm+MUGtP8zvOAE1A==,iv:S9F5gGB/beOg/3j/L2wi9QVuLZTzXKuZzzDiMS19vHw=,tag:TRiFjX3E9+9ZqkwBdfajGQ==,type:comment]
    MCP_SECRET_PATH: ENC[AES256_GCM,data:5I9yXAsyjeJLaJ0YKSjIRft1oOjVgg5d20xkADAMo5vrLfEWyg2BvC0=,iv:jW2i9j7isyiYHuYy5RnpjWD2x/GWLQgylsCV0f04NI0=,tag:6OS0CcPRW0T9vELLPKKPTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT2M1Uk8ySUJSaGJPUkVr
            emNNRTV6cHBIT3JhczNBVVNZU0dITjhMZmtrCm5OSmJzM05WUklNeUU4YXFLbEEv
            Yy9BUXdBRGJ5L3NNb1pma1F1dW83blUKLS0tIHFVUXlYSldVcFZjK2xpMWxVUzBu
            YXlTT0JTNUNEWEJxNVR1WTVXK24xeUkKB0ci/GMoVGv2SDelsyqQkuKP6lertAK5
            n23RJdZDKW4XrftFkIHJaB8ao546glYHBqltPZH0UJrQxrtG40MSjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXblVXMHAxdkQ5VUxRR1k1
            ZktJTloxalM1RkNVZDhhODVDZmFwMlZnQlZRCkZTNkhmVjVoYWloV0JiNndCZ0Mw
            NDI5ZGFJYWUzVnFoeTVsS20wNENENkUKLS0tIDR0aDAvbnJiQVFvWWhqUm9kdjhE
            S290MnQ4NHNFUWNFU3Z4a085K3M4MG8KVAOgCZsXAFScIs9w+0/bkdJkLWdxoH2i
            VOTAm6PUxEy1QsqlxdQYyrxLPh6bsqnjB03Ii2vrdWALNvurdgf47A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T09:26:43Z"
    mac: ENC[AES256_GCM,data:eNo+NKxel1HRghGdU2B/dSGsBjoDa4szZ2FO0OfQeQcFsWBfPdHbnqZf8mjsBzkDWqoAenV7hfxYinG9ALMSp0jDaLvLEbSanNCNpQQadxG7IxpTZHLmc1Wq56QtEIBdD1V9isUAwL11kb0LamVCku2k3SM0UjGETIJD5MtLQpk=,iv:uQ5eJxy+7qRDF74SvezD1wthLFWOclWrEAKa/dBuijg=,tag:eGFcMsrd1imcroMkBEMeDQ==,type:str]
    version: 3.13.3
