apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-url
  namespace: gatus
stringData:
  url: ENC[AES256_GCM,data:A1tfp6Mf7M8NAWc/RFyW+UJerFAoPulebDdwRyqiDecvL+UPJ7pifIb5iF9qX8+Fjxu18jHmYfbey283GhJbY9HcWbZfUfPSQHH8M5UeVQ+U,iv:XjqLbkAPzob17f9lUC84oXgYG6m/6Mf6vWFpdZGwhnU=,tag:/fH68UKRuuYn3jlPCKVrqQ==,type:str]
sops:
  age:
  - recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdzV3cTMyeXhsZ2c4WlU1
      M2NKc1htekg0N20vbjROMS85ZW1JUC82b0VBCmYvQnJKdVEvenVaWkxVRUtTRmdH
      bGNjcTM4d2dqRHJTcU5mT2UvZEk0TzAKLS0tIERsREdvb3R3dWUwNjV1MTd3TFBB
      dFd2cUU2dnVQallQdWJ3ZFhQNDJyeWMKeHSnDZs/LXezRbX0cUY5ySISZlMvD6PR
      DiGnUINFWNBfX2saCmnenDrDZkLBjbFCVFWnRrMgNfj94D0IVc+EOg==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T01:11:24Z"
  mac: ENC[AES256_GCM,data:vWYecVz0TOuc6O1uCnI5DRit9QwxB+mm5qDU6I9pGX4J09onY9QznpuDNidT/7GaoIJJi4cy8PHCIlZo/ISR71uPWj34o7TsBlIkFkymhOtdcDMAkPJ7xJBqnh4QEIg4ep8nAsngI+vdq/Gf5znyJ4LBN8kYbnKHE81zG65mIE0=,iv:COdylTEGvFU6K0VA50CCOuGcrkxbNSIF/Agc5fXfsow=,tag:nDmu+1bgQWXZKBdoUsFyUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
