apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 12h
  chart:
    spec:
      chart: pihole
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 12h
  values:
    persistentVolumeClaim:
      enabled: true
      size: 1Gi
    serviceDns:
      type: LoadBalancer
    serviceWeb:
      type: ClusterIP
    DNS1: "127.0.0.1#5335" # unbound
    DNS2: "127.0.0.1#5335"
    dnsmasq:
      customDnsEntries:
      - address=/homeassistant.internal/192.168.0.200
      - address=/pihole.internal/192.168.0.200

    # unbound
    extraVolumes:
      unbound-config:
        configMap:
          name: unbound-config
    extraContainers:
    - name: unbound
      image: mvance/unbound:1.21.0
      ports:
      - containerPort: 5335
        protocol: UDP
      - containerPort: 5335
        protocol: TCP
      resources:
        requests:
          memory: 64Mi
          cpu: 50m
      volumeMounts:
      - name: unbound-config
        mountPath: /opt/unbound/etc/unbound/unbound.conf
        subPath: unbound.conf
