apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hajimari
  namespace: hajimari
  annotations:
    gatus.home-operations.com/enabled: "true"
    gatus.home-operations.com/endpoint: |
      url: "http://hajimari.hajimari.svc.cluster.local:3000"
      interval: 60s
      conditions:
        - "[STATUS] == 200"
    item.homer.rajsingh.info/name: "Hajimari"
    item.homer.rajsingh.info/icon: "fas fa-sun"
    item.homer.rajsingh.info/subtitle: "static app list"
    service.homer.rajsingh.info/name: "Dashboards"
    service.homer.rajsingh.info/icon: "fas fa-tachometer-alt"
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    sectionName: websecure
  hostnames:
  - "hajimari.${LOCAL_DOMAIN}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: hajimari
      port: 3000
