apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud-credentials
    namespace: grafana-alloy
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:i88cy+RgQiOTz/0fBAjmuEt6odH8lzIn2D1RU/BoAQvO5xtX9qTBoqdK5l/aAyu3qYWa4rP/7w8Xclm26W1clN/UyHdRrmUwDQ305TDnLpYPkvkbKHshvZHO6pezRZ15tfZvio+zjvl1IavKQa1wQRy91p9/g6CNr0J/DKYfXWUSenE66v06cVp4CXLnUg70/kYIwysR27RNgNbjHSFg+Q==,iv:SkoVt27Mb2KOezBEHdfD+Z34+YMqtnJ9JyH2osbS1o8=,tag:uS6D15IeVekW+0aki1ygCw==,type:str]
    prometheus-url: ENC[AES256_GCM,data:1fkSyIu/wNLGB8+WjzlLNZASuxOWDRDvGrSiqo5NL9Fnq/OgrxjJ/O+mW/WlwUqnxui1wNsbnEhjTO0krxnDFUSa4mk=,iv:KhSF5odVtRHEwTZTPJP7U0ZNY0Ncjg6XfsWF+DxP98M=,tag:k62z3lVIQZRGD8ft6Nu3ng==,type:str]
    prometheus-username: ENC[AES256_GCM,data:K1nZV/1phw==,iv:sSyUiyxaiNoVkhIz2CLyHgwHMLco/acnrkGkbZqie5I=,tag:XPkf7EeksaqetxU00SUObg==,type:str]
    loki-url: ENC[AES256_GCM,data:I7CXDOOBw5DK2Or27DFynMhmoDkKGXb6HxCSBVBhzzHHTwsvyZ03zTtTG9MKPL4M34I=,iv:ttz+8BCebH+uxQ0GYRUNArU2y+ErF3ANhnD4uusYVeo=,tag:Bd8mc42TJohekEmU1mD6Yg==,type:str]
    loki-username: ENC[AES256_GCM,data:d0gqRT+HYA==,iv:ouP4Tm5SxiM6jc61hM4bLrHmrdkLanGZeM+/mWsMhw4=,tag:XpuAhHTxPYdkwMfwn65SFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYzV0U1BxdXJVS24zVDFu
            VTlQMHdEK2ptSXNxSmZaMWdwZFVJdytoRmlvClZhYktZSEtRcFBuWEkzYTlvcDg0
            VkxNZzNIaDNLdllrbGx4NUNhdGhVY1kKLS0tIEwwWkdjSWtwVVROMStDV3R3eXZ5
            TGFRMkpNS2E4Z25TYVlHK1VXakJScFUKuLnpRNN3bNTQBjEIh1AagBR62uTQWoN1
            hVjmx8SnIRHbbjhG8v5S49BxqEba1dSMse+P6l4RE5R7RbXUn3AaAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T00:42:14Z"
    mac: ENC[AES256_GCM,data:CEoW+03gAXQb+fACeI8nEwp1Gmp+Z3ZtMQqVylnGU7oQMoSB6T66HQebnQPJk1gLxrASZeY0OSllwyWqku3ztB00oKcSn0tFZcZTkcojZjfOGhOayFWCZitzvm/LzN9Cx1XZHp2lOIPsH5GrEyA7MREYw1DhbP1cJCb8Ws42EMA=,iv:PH6PtVLfSB85xaKj8yVLq4iY1oJxVPb/k9O+YpxSaP0=,tag:WGXsOhkwQTTEhKUX90RDhw==,type:str]
    version: 3.13.2
