apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - pull-secret.yaml
  - configmap.yaml
  - secret.yaml
  - dashboard-internal-auth-secret.yaml
  - networkpolicy.yaml
  - agent-serviceaccount.yaml
  - agent-clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: ghcr.io/hazim1093/hermes-agent
    newTag: 1c9433897c7b8a3b2754a84875e8f86d0a42991a
