apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: hermes
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:8lPdgigId09pdq4gU3xy0pe3rf4vFIF7/fo0A8Pjm+v8T2XjmHOFinXR6vZkoh2IianjeY2HELbFNbm0nq/nlM7gsiFqhml6O9FzGmSoUSdpAzMUQLjS7OWfLsgowsainsPzB1lLMTmGBu/XGi0=,iv:Skd/r9RQyysKxjiHzHnHbjC73nLnDY6dqH7fDpOiiYA=,tag:GsZ/sCg8u1RYf3u+W/IxWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN2g0T1Q2OU5CMEtiQmM5
            dERwNHNYVnIwbFZqUHNvOWw1bkVVVG01L1JRCmhNQUxNVVFjZE5zeGsrUlpMcHlF
            QkIxT1E0aUZaQldNQXlCZ2NTQXlURTgKLS0tIGNoVDUxSkxmOXQ5U2g3cTI1REhJ
            c1J6alVvNm5NU1FaV2wvL3l0aEdHdDAKMDvrqSJl9gSboQCgYRYb1gURW4RMfiGO
            8pAARmZynMu2SmzSJRk6p4wSW+dRXoAILw6llL0ubWncn/i5h+Uqvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkblN2K2lxL1dyQVNEUnFo
            cjVGaVhWbVZ5SlU0cklENUp0b0haclorUmhNCjVWY1Z0UXJFcy9sRGhkNTRFZEJq
            STU2LzRjd1kxdFh6a2k3WnNodEJ5akUKLS0tIENVajBXRmFwODFsU1FHMkxKc3NZ
            cncrUEtRMWVTUmx1OHVUUXZuaXBlbTAK1GMTzLTj6++7fCbcWbQRKe4YQZbfJ+ve
            ta317Gnrsj3AR79GQhRTfecdW8qbaJ3lBAqtDSXO9045zFW1UqvnlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T23:22:44Z"
    mac: ENC[AES256_GCM,data:Cb2JIaq9cA2CH3llpIi/MdhHGUWxtmSoEnLkLUuEFpepaKZ4eT0+fudWnlxg1dbAZRi4wnh/u/H/Ll6jyQantCguWxRvXh9GpuzVAGQMt/n0/FEeVz6rGovfXAoh+jV7QScc/pF2B/BBaGWnQ9B81C45PYqM/MjJj8wUUrhodgY=,iv:dwtRgkh5z4a40ZMb+rAYt/O+pTJqh7ARXoYq1+MxB2k=,tag:veAOPsEiB2aMB7UVWRgVqg==,type:str]
    version: 3.13.2
