apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: hermes
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:8lPdgigId09pdq4gU3xy0pe3rf4vFIF7/fo0A8Pjm+v8T2XjmHOFinXR6vZkoh2IianjeY2HELbFNbm0nq/nlM7gsiFqhml6O9FzGmSoUSdpAzMUQLjS7OWfLsgowsainsPzB1lLMTmGBu/XGi0=,iv:Skd/r9RQyysKxjiHzHnHbjC73nLnDY6dqH7fDpOiiYA=,tag:GsZ/sCg8u1RYf3u+W/IxWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcERzZFBTSTZ2bXV5MzJo
            ZG85enl2b1ZKSkZYTmNwbXRPa1JwMEU2R2tFCmpha1ByN1R6c1N0OFdpT09pLytP
            WVlqNUQxVE1yU2NPVktxUkhjN0IxYUkKLS0tIEsyMzNQbDVTbDdxWml0WHBWUGNE
            UXc0Tnd6WlIyNm5WQ2k1b3VBR0phUFkKdq7v40RBYZF5VxJ3jzVC6HpnNmFT8i5x
            Rdan/EjcSm22G012G+ZoSk4kBs5COjodld00dHJ7t5Z/caUmrirsZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T23:22:44Z"
    mac: ENC[AES256_GCM,data:Cb2JIaq9cA2CH3llpIi/MdhHGUWxtmSoEnLkLUuEFpepaKZ4eT0+fudWnlxg1dbAZRi4wnh/u/H/Ll6jyQantCguWxRvXh9GpuzVAGQMt/n0/FEeVz6rGovfXAoh+jV7QScc/pF2B/BBaGWnQ9B81C45PYqM/MjJj8wUUrhodgY=,iv:dwtRgkh5z4a40ZMb+rAYt/O+pTJqh7ARXoYq1+MxB2k=,tag:veAOPsEiB2aMB7UVWRgVqg==,type:str]
    version: 3.13.2
