apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:DnD0bNPoUXUODc03y1PrXq7TTd0Cyj6XWVi928CtkTa/skU=,iv:TnH0rcrVTSYXQlzjktQQ1LWmLpfoLi6VAbCuAhUQsYo=,tag:sk5Zp3Ro1wZ3cKkWWKyA5Q==,type:str]
    #ENC[AES256_GCM,data:RYx9u4MY2Ukmls/e/w4f8Q3CZdJd/w0Z3T6bW0I+MZwmEtHcjg0Z/setB4/2PQoYlxVrhc7noqzBhJGCUTJEdoMp7AW5w7WHIeePoZ6A++1c0Z6sorNK4l9DOnoTHSc9cXuUSI13pCeUy33U+9gsng==,iv:UZJKwDKibjIemKsRRGvmGphz0oo+9rR6UE4hVmd8pQ8=,tag:TorYOvefxbn1giRO0oCf1w==,type:comment]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:MaPKTJe0UhPIONF61Tv5tmBUYE3DrxRKbNXrJzvi/EitvUk=,iv:fvtmm0FqGG4EsilcZnF2viZlZVZoeS3e2PxcoU1Myog=,tag:XmyO8wc7lvT7auMQS3IjoQ==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:/uyaDzfctgEB/bgmSTBEN60XCOiHPDOoK4k5ItQ36kROFICkWJB0y8xv3mKrUwexdaNTXqY6Q3gJdsO3OmVRFw==,iv:QmA3yBd/DAHYejpK+laAhp3ioIglMwt9A5/dr1P05pA=,tag:1h55leFhQJtgLyoD+XfqjA==,type:str]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:KwU5wOQ8ZDuElSD4NhcHwqT6jL6nVtoIFlxbqw20+OgrHBKGArQ1y1x85G1F4q+Pkg//wF7s4KvAAA==,iv:wp755FWgYFs/3v+GJ9DCFlbVhLs9qb8dpCyyVz5h/kM=,tag:bF/TDpUYU+lbyWYy8yoFfw==,type:str]
    SLACK_APP_TOKEN: ENC[AES256_GCM,data:Br0NkyO7XETIpVeGrCcwJ8yYJ6KWJpJluXff9wVO3n9Im4o3moALlfdlIbtmt2I/UUCWtgGiOvmK3Jv0oFa3+d4V6J4nNA6zIdV6QWRN7uzopYlvjJvmbzA5NjoILhgxqsg=,iv:YFhJ5Glm9wtRvLOkHlVlJaezu29SRjpbWFcikScvfP8=,tag:N5YOgAk7/MpOKYwDDRRoOQ==,type:str]
    SLACK_ALLOWED_USERS: ENC[AES256_GCM,data:yZFaS7ScuuGebfM=,iv:jdhflPDt3fYjiYyxnze7Vz++7zH1xWT34gb1cWj/w98=,tag:QYRwtfuryM4eZ3dn6XKq4g==,type:str]
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:MDaeHg46rdDGi4Jp71YFM0JZcN+KldJibnRbSEiqy8DqwsIIZvLsjpnD,iv:V8Z4n1UZcS54juebE40eC9wW1jW6kjv6oyfNkUd9G2g=,tag:uuJtALjGryt7ZE8jNox1+Q==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:pARgSv90JwL0oJ3PYSkrw9Wu3+fy9JvbkOSZFrxOXTbsDF5tiefRm+dRfGnGGw==,iv:/Wrn2BchfmhUc2bSIe4HtN/EaUYD/pzSfNaAzRG7K7E=,tag:qC8ebVrIA3crDZXtmBg0Rw==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:4g83mTqJaTlp+w==,iv:GMUPa962pLfWG+Vk+IKITGMfpMTIOjD8vO6Cgb3itV8=,tag:GtyvPuDuNQ8kgh4ynq2GfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuem5idE1GK0ZDejRLeEp2
            dHpxSzQ2NEJTUW51RG9Hb2NROGtaaGVsMVZVClFDK3FUYUVxNW1kWU54TjBncWlE
            dCtYRjVmNDY0NjgwdFJzeGJON1ptSk0KLS0tIHVrbXdScURtbVlaY3JzSmFFVlpp
            SERUdERnRVIwZElYWm4vYkw0RWplWDQKUwf9aNv/UIZ0OBZye80HiOrp3Ei5l8sU
            muc9YWvLmYplgGLmTQ5+9mnOfMrzl8Fn0z5AyVMyBOMRDUuD/Dp5Hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMzk2MEU4RjRSTjdHWjdq
            YU85WlNkcW5wOFMyMXZOVE1XenUvWmlGNEhNCnlUejkrWTBWa2JUSnNST3BTNEFV
            WXovQ1R6OFVzdXhjT3YzdEpXcC9DSmMKLS0tIDBqWURJcEovZlU0a0U1MWNUeExX
            M0k2Rnc1UDkyUzIvdUNKK0JDbjBRblkKzPVyGzp/pwasSwkvUTvK3UwLXISPYnYn
            IpS+UiIg3hUDCAgQhToY7xLWjhyNJhq9u8OQJD2/i0Noe3tEhhEz4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T17:09:07Z"
    mac: ENC[AES256_GCM,data:4oQE+ak41F/M6KQdUcSGLFhH9gyhgDVrAHKWytiLe+PUmgRlDwdfUQ4i1e+xOZ6Bo49UKbYVmYoc7v4iUfKLGySaqOX+J7WLInvgJcYYzY2tumzcwkk/il7bAcBZRFwVxwTKO3w3WzkXMGVEhl3xJSWWefp9X9aTR3TLBOKf8Y8=,iv:FS6dW6kqGvtWnWEnkQK/fhrkjl6mek3IuOY4+USJitI=,tag:1QNJlyI14xa/sPuNpjQ08Q==,type:str]
    version: 3.13.3
