apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:NEDpnFtxJLhekrgZKr6fOEQRJfs+D9PMekGDxcKKo6+4fsU=,iv:7jj8vhqB/z6PgyJxCfs5NqU367lZXT6SpJbCMUoEH28=,tag:4OQHMvgH2say/RnkdMpujA==,type:str]
    #ENC[AES256_GCM,data:wrut7wqFnCks1zlzXfnnKN49NsixZL2Wp+x0k6wnj4NdigDgRgyxae8+UiWxxDldXGFKg75f09PXVSxn/vhbVibwDA+QMe2LwB3D0lmzptgzGRibAEBJzeyFpcEQJ80eMlXYmXTX/D+tUgFPNeX1cQ==,iv:MFZYs2Q1YhSZc7ayVdVusGAjbvD6iBniWiTjSXLrqIQ=,tag:dN/8Bt9uiY69FSvCFVzJxA==,type:comment]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:5+pI4TtVNKdk2EgsvgIT9x+X7zEtOrajBSVexPfXzK96dU0=,iv:vmQXlrjzxBn7oTn/I6lYg4GQu2l5une5Z8ep4eumhII=,tag:gACboN6tBYNzb4GVWAaeVQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:yq8DNxx5FCX6W8n6d2+s8ZQ1qxBaCCeRcL+Sd3WL3TrhwBnlLBC22pG2TxzI515225ZkRhR+OROQech2/eMH6eYiE+myBi4RNg==,iv:fCSq/6B/B61gBTAtNuMryyQx3jkuLfg7DPhkTIpBAYc=,tag:PNCEbelS+cfpf6Bj4plkqQ==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:ZjBHu7v/mQSXj+Z9FbWQNljkBFTSSg1i6jjhazJA5Pw5JXq+3Asin4exA9PKIqYomDEUZS4iesCSU8yUmpVssA==,iv:3Jfa/VF0L0VzdpilagmSMwzn2WNKX1DYL2jWTePhb98=,tag:Q4OsznKfj68sEFLWdUzN+g==,type:str]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:N05xfaAxgzJfuDxdn5S2z4iseUZ7zBfI5trc8eHKkPfBq25B8KDvf02d0FD8Reu3JMocx36rE/16Mw==,iv:vs/fJefba0HOdsh6ezOJd4oofqM2FlwDN2RPYdLav+c=,tag:EBfzEc+EXcWGgY7oNCC+8g==,type:str]
    SLACK_APP_TOKEN: ENC[AES256_GCM,data:ELKxFcQwSguG1Kx0heh/0pOwOc0nPuaJCjEOXO35E+E5RReriF5Bh7pMrINuuwszd5CbLFicO9Fb/LYShZ2HZDPLboF86//V6Ofdz3hVH1rQ6SylOfAhx8LFlOJSiw6PFXU=,iv:Z9wSvZT4OeL0UbfDHJ+v/9iiFpiGy2WsNTn1h/4h15A=,tag:jRSdXmHMEFT0oe3kjNRZIg==,type:str]
    SLACK_ALLOWED_USERS: ENC[AES256_GCM,data:xfjHkm4kjz98LgA=,iv:lSdqQsx1UlyT7z8W47y/nXe/v8GVMf/uoitDk1ULv3k=,tag:Q6DKb38kEFsz47Lu3fT2Tw==,type:str]
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:rBAfiUuTQFn14b9vUllRSqqiWGJR+Doyv3ZGRdNZoWOGsYZyTWkdVDEL,iv:nzn7aqMGFnZQ8i4JvfLjl4Ku7XDOw+55Zc1bXeawDPg=,tag:orn+bj2v4dj5xKHnqs98Ow==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:bVHs3XBj1F3s2Rpe8aTD9rIOfJcJpaA/ss494QqwOZC4maHo3/mSUpBwjZXETw==,iv:ax2Tux9+jO1EKs8dBHAB0mg/YqiElcXCl0jgPVQoYks=,tag:0awAolZhMCk8OidgbCdu7A==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:gRD1+tnz/MWMgg==,iv:hGcB5PrUsm7BWaZxvsk2dBLWFFA6JFgMhfnn3maPm5A=,tag:8lqCCKfTvh3WrT32U8M/TQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSEV4RjdOOXdxaHdVckZl
            SnAwaGtTTjVGekp6aG9TaEE2L3QycjJIaGdJCjlHdHdVWW9sOFF3NzJUNENVbG5Y
            d214Z3dqeUFSNVo5Y1FzRzlaM2VNNVkKLS0tIE9vYmw2clYySTJQWTZFa2VaS3hJ
            ZEk4VFA0OUJuL2dYaEtYdGFUaVJmQmsKSpTpkTIzOoDc1ciyzbz+9CWL90q4/Oxc
            HbuQ9MkOEiBPVC3oBDquFwGVQkwY+I8qZMsKiKEsKvWilht497/jVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ckhUOVVyS0ZsZUI5Vzg0
            bW9RQ0hucDc2N3N6SDNwM3gwSmlPdWlqZldrCjRHTzRMUE9MWnBTQVF6RkRDR2Qw
            NUdTSlVGOTZadmZ0TmNTNDcyVkcyUUkKLS0tIC9iYVZDMThlUnY5bDY4YW1ISmcw
            OXZmZmppcE9icDdXdE51NEcwU0FZcFEKKJAxlhNl0ca4zdSfoMWJrcrvWzEFC4Bp
            /rfEogr8Avb7xerFH6Hvejn0uoBpOpoN7RjFE1aN5rSgK3CMfy/vRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T10:11:21Z"
    mac: ENC[AES256_GCM,data:XwfdbLdPj2ymX8WMmqf5XMvRK1+sgaBJMt+7+CHu6JH9mWyyla50d+M4KRtPGowlT7J5CgIuaa4GUHEjL4072AkNHwyzUVG8Mg28LMgNr6lq8s0UHlYIXuMDTYt3uBIlL1QqYdwb8Y50PUIUd231XXNFLQL+qS7DCXCT5UKnZ0U=,iv:vLmAE9KYLyTvEULGKxlskmwsIij8tK1y5UAtTWUJbHc=,tag:UVTMObBslaj6b7HSKd/eFw==,type:str]
    version: 3.13.2
