apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:IRIT06Z69NbMja1U7WBTg/y8ukz8ofjI1WbPyvDvShzIwtc=,iv:iHdywNFmec5m8sVi7hRPoDPdef9MOBGIeWQuwim7XB0=,tag:gsUMKn18v0BVc+LmNwsx7Q==,type:str]
    #ENC[AES256_GCM,data:aKgliNkF/eE8cdmO9L6eu3Bs0VUF+DQA0q/0BzJpNrIcyBuHubRr2h3bZ1Dw/hJx4MdkfAIzv/n0eMxFsTBDEAP/fMu3sV9C27+UqwEBu4+QNg/th3TEvhrNm0ExDFY=,iv:l1pE9jHQ1fCA+txEAv8WjZGYKdCxY6g9UXZkF8L8e08=,tag:Sak7btl7/NfbFF6RsxWD4A==,type:comment]
    API_SERVER_KEY: ENC[AES256_GCM,data:0a8j8IbQpcL0Em4evceCWxT4/jslZ3bvDQzcU1zBzzpUX2WKk2abzHoYD8xHobfrohEOkj+IC5biHvo8r7rg8g==,iv:EmMRAHRWYLGT2zlt56bCqKf/PkRfnOSmgW9nuV2UTxg=,tag:Jda5eaA2LWKWYb5Czm8S3A==,type:str]
    #ENC[AES256_GCM,data:N1I8aPQoHeqfQD6NSNJd+/hLs07uTOJ1Wc7UqFIEoeUDVYzX7a2KEAp32vSS9PebHyLh30lyplrD9byET52CzmO0wI4JvKUNfcWfwLQOsdotAiSvspPSNCDSIt+F9hRDNNfgTe1l3JylDZTY/gdJuDZl,iv:+XQDX1rbLA1RidlT4bDcYAY+pvwCXq9pnK/rgx9yNQ8=,tag:HjnrhDnWCpsA5iItBwecZw==,type:comment]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:TXZ3HaUeW7h0UOA3KOtCtuFXEmz5BOIOy+G4Mhi+B6hsz0LxQC2QNnlBJtPKNMrgBgDd+1NlW4Lj8g==,iv:8F5vN9CglT2W2gJwsUhFvP0kiHKtbV4aoVCDc1V0Krk=,tag:s7OQyKBVSjS4u/vgn2UJNQ==,type:str]
    #ENC[AES256_GCM,data:uq7RZtX9ojmqQrTJR3SSgOQvtKVazVWjbPG6eLB2jhEabCP/uubvNmYaxUozfU++TxejVsxiWVcFuyoNKfh2bvll8jYEDSYycER/+uF3bt8x0jXSy4AtiYbFbQ==,iv:/Hmwcll/Wkq1f+PaytDkXyKs5fMzxfokP7aRYeA2zJU=,tag:o6Tx0uNggQQexWdCNXwM8A==,type:comment]
    SLACK_APP_TOKEN: ENC[AES256_GCM,data:TJEtZ0V7WgFxferjYudenC2TSb/93kv0TPkD9Y3+qe/usKioSEhIXamUJov6kK+tlX5CP4yerJvlCswycjuVGPd9cgwvumL5TeRknHAgkBn6a1i+RJGFsd2Q/zlcZdLq9S4=,iv:3XxEJuDlWZrP/BwzuGNqkETJnUwmMQ55JojN3AV7szQ=,tag:Ap/5K+K8rYSzPbQR3BmmOw==,type:str]
    SLACK_ALLOWED_USERS: ENC[AES256_GCM,data:72SPkdVpkEHwveg=,iv:vaNnv6QT9CHMMA+A2r/Plbe6Ze3FYmWsd//GO4dT4gc=,tag:hrro7huNu8YqqPKY/iVq9Q==,type:str]
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:2nykPJ6hmL3SM4i3XFLlMBIsoJdGTKh3GOwpMqeihqHmOiuTig447a+d,iv:BGZX3L9wYsyOfQJe5YOZaENMVkygrkvI6oPApMMg1b4=,tag:NAqbyhMvNVV8210tw0q4Dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZnpxcnN5YXVSYkp0Wmxz
            U3NjeDRKVFRuVVJTc1o2UkZ2bTlkZXhrRFFRCkhnUkRaRVY2ZG10WXNkN2cxNzdw
            d1VsVjZ4eUZRMGhMRjBXZUZqN2xEdDQKLS0tIDVQMzlscmMzanVXN1dLV3FZT1I3
            TXYxQUxQRU1iL1dwdytVMFlxbjIvQmsKERJNXKpzIS8e1G2SKMAi20kugrIA/pNG
            GHvTdHGYPJ84jYv1J5uDfIWjs/2XOc+gwKgWRhGqYxvne3n/hzOW3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T23:49:15Z"
    mac: ENC[AES256_GCM,data:GwGiTWbQn52GVrlZXW7JoBhfUPqbW/EoE7I7goNJL2qCy74ewEsR2zp1ljppcl30rJAZWisH67cAUT/n2wXVe9qxF4AnrBsuDGwUhN5wddg6g3DnjjLfLBjB9ss5KCFUMLUlrcdWdrqdh5sJNbpDx3AsMIt9ExBbDL39CHVHEY4=,iv:2+FcJoUL4TCCbd3O1Te9Q8IRfI38wlGGPCxUVmBwk9E=,tag:A0GdpmyJYNKxgAoEEFR3xg==,type:str]
    version: 3.13.2
