apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pull-secret.yaml
  - api.yaml
  - frontend.yaml
  - httproute.yaml
