apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: screener
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:0kI/xlHoyS7pzuNtLPuI13yKdZvocWnXWxvvMN7iAvCHj8VjHvqti5+v9hQgQvJgcxSCa6nEv/ZtXFtdtmBhz11UY4xMoGttjfQnDl2MI/gcbFfZIS/UOc5nnb4vOW+m+NdL0FS+XYU3bRsZY80=,iv:B8mEZ0fZ2uCYwGd2b18GEOI9zA+xV+8jP88QaQ15Ni0=,tag:2Lwz7shMjf+Yhj+FZ/OnHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBER080bkJsY1pvZ3BHdEdE
            eTVBemlFYUZZQXdDWUt5NnVXNFA4bk90L3prCjd1NGtrNjZGL3d1MThIWkgvVlFp
            d3cwWkVmQkVuQTFpb2tJMllZRXBEeGcKLS0tIFVJNlRET3c3bGRiMFpCUHJzRU1n
            L3dHZ1l3ak1TQWQrZStMbFJBSldNcGcK5g3CqPfD7HVYItXVqDYhbrr3czEYGYFF
            aOpuUm2B8PTLUOmg3Gi8lpb4+A7QcM1syUA5tM2h3UUL79PSXxQ3gQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T10:29:39Z"
    mac: ENC[AES256_GCM,data:I5RSjCoDKe1Ex6mrDpfqew1EKl71UmPzWly2v7+hzxKwyZ7qh3E40kjGsOBN1oKAo3F2Zp5NZkxKrv0T76+T6CRIcgYtFjUcGv/9XAVEhRjLHDrNr2T1eYZfnv2jSgq91BW4Ep3gNhYlQhcTtmuGtCRrjRe0XMEOJyO9TVrxiz8=,iv:S9jx0PZ0KNjhTZohqv8iadIyg+675o2nYY3mTLgNkCs=,tag:NGlXTDzHui2ZzDSulr+NjQ==,type:str]
    version: 3.13.2
