apiVersion: v1
kind: Secret
metadata:
    name: screener-secrets
    namespace: screener
stringData:
    TAVILY_API_KEY: ENC[AES256_GCM,data:5HmDzAqIIRTGtKHifZsBoJdtoGNk0jlOi1KjZ2TyLwb+ydP9KjQIaJ0sWNyIaood42TvL2+YakA1OQ==,iv:XcoUKYUdfDmVVlT68SRf8VN142Mu34Q6o5VZv/u/i54=,tag:Fzt204XDqjYAURwRFKKzaw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:8bTehejoWcnMnzZn6Tkfnu48zp2gDXbHT7yOZ98oXzXmmJAYpx9YM0t9COl36ukRRc3thk9/c0XHEx50nPjjkdIXM8YqUr5iAA==,iv:RRdpz8qKrcn/aQZPYC488JfiNV61a8QGcsK2T2baCHA=,tag:5aLEGG5ffNYkFBZBKUmVhw==,type:str]
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMjFUa3U3VEpoNXNFR2F1
            TDN6bHNBTjJIYkk5MERQT05vZDJ5OEFIVGc4Ck5VZFhRUktVSmpkajVUNVpmcWdI
            ZHppZEpqQkczN0FSN2RvQkNUWXJ1cFkKLS0tIHNKeDB5eU83K3h0eGVtUCt2dEFt
            QWhOaFBwNUhpdlh4VFRPVFNUc1FndEEKoDR6hNjr6jnizPfQCbXnucQoHmknTw/K
            ktbB0LDZTl/LVxxbMUZ1Mwc/+b/7DhbLuewC6XUD+k85k+STexOFGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T10:21:51Z"
    mac: ENC[AES256_GCM,data:qh4Gbnbn7BZUZg6uF45a35SopTKZU6xEgRxnhUTlmsUsply9rwtbb0/wVMxISldAlrjmhvhwZd8zpKuxe5dH5ej16CyIorlDhiYEIp07L1ZYlBpMHF6Z7vlw6eqOTQqgzlni5fm/lawKGQaCvdU45+a4qBWcpZI+Oppeyq7AaSU=,iv:6RJUPAOI1MvrwOOeAhIEDH4Ly1/XpLVb6WdSOheCW90=,tag:Cq/r/DI0XihCj3zxjRTBfA==,type:str]
    version: 3.13.2
