apiVersion: v1
kind: Secret
metadata:
    name: obsidian-vault-backup-livesync
    namespace: obsidian
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uoFPhvO1IIOwYWXxX1vudhUZyhbKuS96wDSlqm+87M4pyExXnL41o4sPbgtl/LJAdlV2Imrl2cvFs8KK/JypiWEie17FSuUy0fNIJQ==,iv:oyoP+3vYGW3V38N9JKWCOYSiX7Ktlf+qLAhkje5l3bQ=,tag:EDZ1TQrv/AKIc8ZexA4Q1A==,type:comment]
    #ENC[AES256_GCM,data:nzLDWmvLMUZdiXIa33rj9r43lS5ay1dcdKn6U17BsUdngm74q/+B1ku26YlX2WY=,iv:/Lx20pbMpzTtFsRfH+o33C0qWaNizDODVHLcw+ipJl0=,tag:W9E/lckUV/y4an4HAsh+3Q==,type:comment]
    settings.json: ENC[AES256_GCM,data:Et+PVsMdqV6pI5Ia3CrmjoQVpNlMwu3vTUXPHu24CsQAlQro1WXzu3CUT1gGoZG2TWtqGMYEO8O9GIw6I7WKvnO9aRGMOt6LwuWvauuYNQpAQHEYYXEAXTUJX7j51tCR9QGp+KKrqvoj6QKb7eqcs31quGv1xEK+lKCn/zRiCg260cDsrHu7Lms9zs2DAV2miVE+/RnO0d/q7mLyhJP6wOBFXNMB+R3VxfEcog9o9pqy5Dygz0GxRkm62iZsKhVaiAyQLw6SLRc2jJ8YuJYO95aUHSt2IvcdHN7iZ0I8o3LMYeZyejtSpxnpihmw1lBCRA6+5GeDs74ci10yGdTxcTJhpIv88knnCvJ82k5gj5ba6WfMvHqkjIZMxmUKau15bszadMc=,iv:dZufG8T01A7i6eSKs3IYjoqkvp+8Z+xK3ZLZ41Zx+f4=,tag:F1yMeg/j3E3oIC+lZkQ7mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaTNZVHV6L1BnUkdoUWRh
            ODJJcmpNS1YzeHlSQ1g2dEs5TUVORzZFU244Cjl3amh2MFdSUGJ1WmxoU1djMlFO
            azlSaUhrSFA4dFZFR3VUeWNxaW1HMWcKLS0tIGQ0SlA3RGFTcGZYT095YlI4VEJZ
            cGtuMHFxSC83cGR0Y0t2K2tydTEySkEK+sDDNuh+iyr+0XJyc9p7O3S98x0swAYi
            TfZdpohNmceabdFjhtCy2AvaFTPY2VRFdU3iScR6k5MBHAeCUEqoQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T21:54:13Z"
    mac: ENC[AES256_GCM,data:NlXBucbRqThw7B00hD6NLrX4QA4keFE4elHGA/1CsUmHQSSEfl3Ygrqx2jANvSZfmrQAVNS895eBl1l2NH9nu6BsLwPwzkcYyBomD9i6Z7Lks4COnwDXHoUrPVMsU8ige7BoSSwcEDemPdGGaYDhl3k8YLfzqNxTNk+l8Y3M2jM=,iv:scErlW9grmPk9ChXwD2zCqU9VbTqlHfNd312DiIj9eY=,tag:vSM53996mWBD6Bs+uXL4bg==,type:str]
    version: 3.13.3
