apiVersion: v1
kind: Secret
metadata:
    name: obsidian-vault-backup-restic
    namespace: obsidian
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Dlruv19mJBkWNbv6q8tCGL4CGd669S0CB22ZgJZvzDj15UEwpqNh3A==,iv:Ifm7VyQ39yYmw3wgxEkB6ZdKF8lkWIL9NUlvNE5RNY4=,tag:RZtUsPxD9nOYBh7qOCFL2w==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:mAuTXuRsNtV8MTiIhmPs6H4izBc3Ndzew2G3YY2kFR4LSlF2ZoEzsQKpvU4YDAubAoM3Op9DuIHuM1tLW68rJWsbRXMPN2/FlEsD,iv:HiQrnb2unCfZUfQLoXxBthxhhoqC9AVJ8Gy74mkLDvs=,tag:gP68rZ7IP6pzdoPfzmt+Pg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YE4rmMK0q25j/ISQu5ZYGyjTPXsDuWGm,iv:soSBKRW2v30S7kYJaGC/kEyp+xVUKEma4Fgd+ZQiNEE=,tag:GG5MawiIZ1UC92PePqPFWw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PbGHUEUx3+YeXvPa0htWFNm6bEzBIvYSUIriRA==,iv:VcBwnM4fNYrb8Pdkyy7uuAVEf4T32Aj+hl6wVtlyux0=,tag:XoQwoyMb9BJ24Y42kfqo2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVmJyREZGc2szRGNNUHdV
            a1RGcGszMU9LcUxjZGRUZys5dTdvUXE4SWo4CnZJcHJHTGZOdEl5RWJMUjZjNUsw
            dlBPbFlhZHV0MkpXb09SaGZRY1FPSEUKLS0tIEwzZGhrQkIvV29sV2RuTHF3cEhG
            Vnljd0VYaWVjZXJNN0JoZXdFUW9GYVkK/6maXEi6xRyCQw0rKYl/NXaNhBufayIF
            AlFyXsRAapFy+wJGuVrc4YgOWBC8AS+yr3hQ2/gmeJazPkYY8MGWqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T10:45:47Z"
    mac: ENC[AES256_GCM,data:wJ5HpiteBtqFXHobyRaHf/rpOHe6eo3RHi1ZDA6bznI7n+o5vHBg5jpNc5tLODE7fYsp/d/bY58tMj9SlBo1IeDjjopDxGtwZR0smYmNlqPnld+1+SOyrkKLC1KmdaOBo/VQZWlJp14Y+M68nQ+H9bLmkdCHfajtbSfoh19CqwY=,iv:TMmlDFEGZrM6NDgHlXa+h5BL1jKkcVh53KiFjMb5/60=,tag:2bG4ZDR2LFH1RBvv2DDWRw==,type:str]
    version: 3.13.3
