apiVersion: v1
kind: Secret
metadata:
    name: obsidian-vault-backup-restic
    namespace: obsidian
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Dlruv19mJBkWNbv6q8tCGL4CGd669S0CB22ZgJZvzDj15UEwpqNh3A==,iv:Ifm7VyQ39yYmw3wgxEkB6ZdKF8lkWIL9NUlvNE5RNY4=,tag:RZtUsPxD9nOYBh7qOCFL2w==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sXfZ0EpNrzVccBN+Sot5651mddvWe2T1zoaaOw+gTuEYHSFDTkg3wjk2CXmC+SRpMKaPBbAPrWq5/V54Nc+C4mhw8pXYwEi+Zxm6WHlJSpcERHMe,iv:+2TK6+391BiEbleTn2evUggHrVNqNGYCYFRf9u1LJ34=,tag:5miHpC0dXKhfs+NvkQetQA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:G7Hf0PfEckFwnxQ/ORPnk7I6xfNX+vU78Xx4AgQgvr4=,iv:qqYOjDFu2PBLbBVrydZ6WWEZX3VheqzMO2k3zXXyczc=,tag:KlRzxblS7ilkUm7mGX4qwA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SBrhxu6zYH+oe9pagJuiYYuTR53QTZTxXKtVGcwDe6EKTAwTHkvFR1UhcwePGjH/uU+63LOxnoUctYBVfGspxA==,iv:8z7oWGQeZ59M5ThU750U3IJLaXweM0jXZXYicJw6XBQ=,tag:2+eVyqAdeHnt8qGC8HTi7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVmJyREZGc2szRGNNUHdV
            a1RGcGszMU9LcUxjZGRUZys5dTdvUXE4SWo4CnZJcHJHTGZOdEl5RWJMUjZjNUsw
            dlBPbFlhZHV0MkpXb09SaGZRY1FPSEUKLS0tIEwzZGhrQkIvV29sV2RuTHF3cEhG
            Vnljd0VYaWVjZXJNN0JoZXdFUW9GYVkK/6maXEi6xRyCQw0rKYl/NXaNhBufayIF
            AlFyXsRAapFy+wJGuVrc4YgOWBC8AS+yr3hQ2/gmeJazPkYY8MGWqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T22:02:24Z"
    mac: ENC[AES256_GCM,data:ylSzy9mwmzjZj+a9Q3iNSgghqqTNijc+WVW6sVDekdrZlrNmpjcgen219dTqJzaXtoflxZEevSPxb5kC1thXFD3qYmb+Oma/sUmqlrLk0QTcGcQwXVaCAi7TOw3cVkNl/U1IAD3JXy9f5tlhryVq7DR+0mKrTZKAwevE1fEKHm8=,iv:kv+j0T5JzR7N89RhpeXyrg5IpLdnGoe6nP+gmo2VINI=,tag:zruEKCDVDzi2CcsntmRpTA==,type:str]
    version: 3.13.3
