apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: arc-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:QnKDE6A6jVOdSPS3NwLqtDIEJKz/HotJWmK86V9REjNNo6QG5huKFfexpI7D1K5rAp/ZDsChuB0g8iSRnoX/XA1IRdpOInI+2ChAiwxDNDVC1i6M2nzZootyxCuuCVsPuscJAYjcmLDNAfq4SxI=,iv:rJIJNMNfxxvLjr3AJaAmWQzpE8oFf4oKgT6RmGpnrWs=,tag:RochAFIzA27tbTueCOOORg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDekh5MlE3T1d0Zndmd3BT
            c2R3anlVOGhFQkxqdWROS2VzVjRVclh2TFZrCkM2NHdSUG9BSm9sRi82N1pOdDVh
            d3YyL29yTHZJeWI0R1VPUnVYUFNFTEkKLS0tIGpyYll1bkdna1FyU2s1bHRjTnFF
            cW5qZ1BXWXYwQktxdUNZYUlRSndyUU0KPkSNB5eH9fgRFNyWfPn8u1LcD7Mwpgxt
            jR15tvJKcLQbn3r7wCYv2bAwm67HwKA0jR0nozKPTNIHkpqWygh2NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWjhNTG1FV2R1MStGdCtr
            ZzdMYUxpNGlWM1hsOWdEeWRZdzE1cFVKcW5zCjNWbWx1Qjc4Z1JRQmhnMlpiWnlt
            NjlKa3puYmo5RktrZFJNS0FMWmYrSUkKLS0tIGpVVEdzdnBpTnFrS2Z5RW1VZFgv
            ZkorNFdWUG1PVUFpT0gyRzB2T3lSWkkKQLSGT9pCMxwzskBxKF0k4QdnK0+sIqrh
            caeKez1WHopsA3fcy/ZrEQoRhjUuoketR0+bAGvwq9e5vXZZngBDKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T00:40:41Z"
    mac: ENC[AES256_GCM,data:BewTSFB14QyKuu6RV52tR0JN811OXucUxFl6otq6h5Y9ub2NI4md8uZwcbabxKqJ0EL2dnzjfYRRSWqTy5TKgFZdG5aa8KdKOQrBOSmcGR76Xn7xrVb7AdxARLaN7znolq9r4Pzm4ozQnPUnbU+be9S9e2b5VcGzdgOSZb4+vbg=,iv:XkK5TZKNKJPnaizCXTSSXhftR8mxHLlN2LmJFE9lMRs=,tag:1AJhxm31nRjPHIGMNAMASg==,type:str]
    version: 3.13.2
