apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: arc-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:QnKDE6A6jVOdSPS3NwLqtDIEJKz/HotJWmK86V9REjNNo6QG5huKFfexpI7D1K5rAp/ZDsChuB0g8iSRnoX/XA1IRdpOInI+2ChAiwxDNDVC1i6M2nzZootyxCuuCVsPuscJAYjcmLDNAfq4SxI=,iv:rJIJNMNfxxvLjr3AJaAmWQzpE8oFf4oKgT6RmGpnrWs=,tag:RochAFIzA27tbTueCOOORg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL1FPeU83aXAvUkFiajlO
            NnFhbktvdDJwWTJqNHBId3VpeHRFc0cwbHhnClNJalZyak5QdzErQVM1UGtHZHR1
            RnpwTkh1dytkTUNaWHo4VXN1TjhsRGsKLS0tIDQrRW81ZW5HOU9yWXhzTTR1azFm
            TEx2UURGd3hscU5rUW9BM0YrOFdSQ00KQtS/umx8mNpl3xpenKzqd7Buc9k0/p9q
            02qJqW9Dnwp/wQ+18sichJCB931oIvIEoexAE4W5k3lTtpEJye5bxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T00:40:41Z"
    mac: ENC[AES256_GCM,data:BewTSFB14QyKuu6RV52tR0JN811OXucUxFl6otq6h5Y9ub2NI4md8uZwcbabxKqJ0EL2dnzjfYRRSWqTy5TKgFZdG5aa8KdKOQrBOSmcGR76Xn7xrVb7AdxARLaN7znolq9r4Pzm4ozQnPUnbU+be9S9e2b5VcGzdgOSZb4+vbg=,iv:XkK5TZKNKJPnaizCXTSSXhftR8mxHLlN2LmJFE9lMRs=,tag:1AJhxm31nRjPHIGMNAMASg==,type:str]
    version: 3.13.2
