apiVersion: v1
kind: Secret
metadata:
    name: obsidian-vnc
    namespace: obsidian
type: Opaque
stringData:
    PASSWORD: ENC[AES256_GCM,data:m92IbYxz+XBam+VftZszmszQ5M71vuFIPfdHWe3Uej6r5sA6k7WrEQ==,iv:3HMFf1tU5PoPHMxpyOCqBDXaNUphHntlK0AEdDfPscE=,tag:EykisP6W4mJGFaP6RKqj7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TkYwWnRNdXNDdnNVM3JB
            dWZncjh1TEl2ZHF6bHdObEJiVXpLc3ZlWlZvClkvdUM2b00rNmFwK3UwVmt4M1F1
            TkJPOXh3eEFxVjJjTUE5SmhBNG1SRHMKLS0tIHJuejVmakVWYkRqMkVROXliKzJ1
            aEM3K0dydmlVbGN6d2JEZTZmL2RMUHMKM8Ahh542+2eBxwfLAO7rKivt0fgYdi4t
            csv1/313tyD5jeLtAcD0KQx8ie1XmMZT0bY/t73snxvtNil9Ibi8NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T09:15:24Z"
    mac: ENC[AES256_GCM,data:UFKEjUgi7m+L54VuhLLGYZiIAJEbxig0yDhxeGLeeLmdxJOHL+qFImY6tv6xRmbtfMt8x0UddC2OOssiCWFQvvH/eFkVq7S/J4xLKU2rwpIbI+uTxdXus8BXjrW0XLYfEMFMcnKQtimfFgvlRsRi2gHL1x1dDQsoZbSPNkHWFrE=,iv:krqhtMKuYR3ijr0qTYYWWXOtNqFzxW3V81CmyyFS20E=,tag:kV8qjr7XQjEUC9ctD9Lc2g==,type:str]
    version: 3.13.3
