apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:fcaUAs4ZGMLWhCvPZJ+dRP4=,iv:hkbtEGhNJeFNOpBR8+zNofPC51/M5UmyWOOA7BfuLzw=,tag:OL7EhYV99FiQZfWcIaWSLQ==,type:str]
    client_secret: ENC[AES256_GCM,data:PSbmdlUOS17+iWUCKCv18qUpC7NZJd40e6V7VMIst1i61E/v5siYTW/qoWxlAq3yj0Sy7OVfOYdPs/A4,iv:PiQX1W+I14UIp/cixNbeCWKwrn2Mhwh7QA3ydDvkwZM=,tag:BUj5zEuWYi8maeFoCDp2mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YzNKTVF1Q0JEYnFwRlV2
            M0ZscnBsU1IzcXp3R2haWWR3cWhGa0FnaGlrClVYNmo4QmxBSDF6Y3R2OWNoU0p5
            a2xTSU85RlFodnA3Qit3eGhwVUVHYjgKLS0tIGR1VXJMUFRDNmVHNGlmWHF4R3FU
            aWdWQ1ZMWjV6dlEvQVY4TmVVNCtVTkUKJi8mksKqSSLDYNXgyCurwyrI7djdAM5H
            PQFiKQCTusEcB/m4QSaghpMYGiCAJLy9imFTFJWsbp5KQWvLlqd/Qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RkQzMWljb2RBS0JlQXYr
            YllyajNTdVpBWEhERTA4blhKeEp6bit0SXpNCldjN1gwS3FnOFhoc3BoZXZrdWdP
            ZVlnVU1yblJIRDVRSFdiRDlkeTY0SUEKLS0tIFV4eTVBQVNEOHNvcTNBRlhpK3Zu
            Y2I4dU9weGhleW43TEpic0I4WWRHWjQKq7Sr/gCdgNmUTFPavo/tiOBaL1qNo+N6
            lrsfEb1w/Ul1kNOZpepNpVzr8zUBrqyAw4JNn9YEOnPGmvfzPVe/Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T10:25:13Z"
    mac: ENC[AES256_GCM,data:UUARUyW89lpu7I0Imlt3vwWdtjeJPXwngnih0u8RrJ51emdVRbUAejsv2etKhNT+VLNvjHQY12K3LhPVIrT3778G1uzuVf7oxwZT4IMv6qPk5f6oxUdMePYdzswM242nfQ6BN/SpU+zEsBGN5Uqg8GJ9tmmD6e2nIFOrldXvXaE=,iv:Fm7LeL3uuMz0ADsw1b+amgySoc0mLg30BHuRtSoMUt8=,tag:XLUloOfV/Mh9icEr0fcItw==,type:str]
    version: 3.13.3
