apiVersion: v1
kind: Secret
metadata:
    name: paperless-backup-secret
    namespace: paperless
stringData:
    #ENC[AES256_GCM,data:c8e/O1+I+hFWkHKeKCub+o2Q7qEVNw8WrxtMLey5ZEMgHTU3f4yK5vY80ksvXCrb20q1oRBZn3jpqA==,iv:lgQX7cu7efgC8JECKqHo2Vw1mcT7LCse27IcPee+zqc=,tag:v91/z69+Pp+C04bFFGMFjA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:TIGnKCjby47Ql6u2cFRdozLtwBOiKSkt2XFvskIHWuuw,iv:aXNtjZJk5KrunLTLP4x1EsBxo6PtFCkVCl5wXtCIuVM=,tag:TgV4KwF3zGF46UJpZ08yKg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Z+nF7I2xyjMT+MPLCvwmSlI+46jhHGVagFiv1iQEuXK/ejilSZ1+IV+sDxQ=,iv:+Bv7iLlY+NC7PoBNtsOtQ7NuX6Q4FLcrksuuuHhMqr4=,tag:SoOXOAtt5lTxJUhqyq0r1A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vH0tSCWbbDFsITY4NtHPfzgLcmwVgNNLdRJ9XAk=,iv:ms1ZhKHhGCBngMZVk2uuGgyiSTCNuhFqbZSNKdgTu0g=,tag:T53sDE2K+k00oh1QxDXytw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:g0UkZfPYhLw8JzV09lMeUhZMb3p9TfxLAj9GRIlPURUg,iv:axBHziPoN/9jd9MB8Ib7mc7COMaZl8c9LYrusFM04os=,tag:f5lOjG+8fRyp7DbkOsPEqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d0h2UlNMWndaRTlXNGtl
            UjlqUU03N3pWUTNyY0lZeVY4cWxOSmh6SWhFCmx6blRRYzhDRnRFTUdHY2liYnli
            VytZYWN5RUVVUTJZSlNCS3NZSlhaWTQKLS0tIFU5Q3R6N20rRWNYK2tmZVdNTHNk
            RitpOGhweHh3S0FNWFI4UzRIaVZkR0EK9lu0DqaZd2vlkzyyO3Giix6KmpKJZGjW
            ng2VTFiu4n7cAeHWlL/WGsWEPzVd2xsqcZSfBK5JfymRKLsenjM03g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOU1wZE5OWFNQcllNSmlX
            OW93MDlEMWRtc1lwMEYraFV0Z1lhK0l5YkdjClcwa2YyOEovU2ViV2QwL05YclY1
            QzU2WEFrRldMSy9VdDk2MTE0RThZcTQKLS0tIDNZcVZqWUdPVnlzUm1LMUdNMWZT
            bHBmNEYvc3gyeE0wZzc0MFFrMzJqYzAKntA8tIVFlnewRScHuM/53INnLnssPYAZ
            ZFjns+1Qg0fawgfkYJIxo34OyhCmaftrVKYOanR+gnw4aac1DvgEZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T10:24:23Z"
    mac: ENC[AES256_GCM,data:MQkaKejw0zSGw5DcFKp0I0ZvGbtQSmtIa0cNYlDsaXOmRIt3nnbSuLdtz80OSRUXXW+hVtARKR94mtztSRX4X6OoMJlyqbgJSALsqm/FLeuZDNu6CFP4E5jWu+6NjJeRhH2SXpK7phwzI11gSv+iEV+ABJQsVdRCUZR2QXVKn+k=,iv:ksZ91SAhT1LzJ+PQ7n5DZ91ddQh7MlTsxUQP9Vw0Iuo=,tag:qxnASelbUDHz7xJLejqIzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
