apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:DDqJcl+8dde5nn/VubMcbPDoshREjmTN5rKmMzpeGaMSS1qLPnhC26WjnubH4e6gibnG/6lw4gTK9e8oeokbCg==,iv:zbfYWQGVCTp/LPq2ALeiz/36kWl84aVanmz/2goXExU=,tag:rLdYDc3pRQDzaY9jspdIhg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:Dds7D0k=,iv:2uhh6dTbZaiiSiXgesTB4IR8FAS0JIP1AG2rZB6NJsw=,tag:bfKkO4d2vrnfd7UBKgbHpQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:HVEg1dyEaKgd0w6FoMvKOLjFDUoF/kxuKb5l+Hhr7qg=,iv:2XFDqlxm2A7PSOykpGHInUpeV1lBH3FBhrAvqz0ReLc=,tag:WxZ7UkKoYECR3bGAIZx+IA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMVFoWDVDeWtKQXR5V3Jp
            MURhVDZNRFRFVEtDK0FJVXU1THUrVDQrVmlNCm90S1JXMjQ3eHJyRE95WnJEZ1pa
            amtDcTlZNG1SNklxNm1ZK0VRMzFxencKLS0tIEdGMVpLbTM2N0tIRzNRcHFLbjNu
            aW1odHFDVXg4V0VWUVN1T1NrZ3BEOW8KLbMpMKujyEzRPR86eVwTRBok7lT+vRdQ
            HsaPa1jJ2n44qTlN8nAXX77tArdElMkS/C2HqUthGjCsBrNSzj21sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MW9xRFFUZXR4YktmeEZh
            byttTzVZeThPNHNYdUdMbmVwdnc3bS9GamlVCmwvNVpNMzRnMy8zUks3TlBjWkQr
            SnVmdTQrbkYwSnM3ZkQ0UldaRUQ4OUEKLS0tIHlubXd5cmZLVndURWZ5V0hUQWFq
            U2t6djlTVE5LWVBpWUgwZVdBenIxdjgK4mXCLLdw9RF8b2rXavXY7PmJDrJO7/fy
            6LeL5jdIrZPOtGoJ4ROhFziamLaQtLGmGHiDlz/1vWcquPJ3frJ3MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T10:24:23Z"
    mac: ENC[AES256_GCM,data:gT0JJnn3RvXZLrjPPtNdvfGr57qcfUZFqDT2ci7Ay1ijexvZsFjKsW3/YnS27V7qmUso+GmefLdME6KOQ8+QV8kbw8nFDO2SaTLw6VjG5vlVW4YAc4JkIhCw5H3JnibArq4Ofn203F6A2lgv46iRT56GnYBeTxTz6Nk/PeBV1SI=,iv:rhTLetmOExGLB9k++ZyOASUqRDlb8/dOGDqa2o+VZEo=,tag:v3+WgF6bw7I+oDYGFA5OZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
