apiVersion: v1
kind: Secret
metadata:
    name: obsidian-mcp-env
    namespace: obsidian-mcp
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2l5UrCy20Bte7fmGOQy8F+S6QterzuJsh1K3RTxBr350+jDEihDFal5VG7nF6w7nTA==,iv:WuRLIgeAe/F8MNJgwNihXcUrZrQWDxeJcA+Je2BqIJU=,tag:ltlDF005peC48235ca5Bsg==,type:comment]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:f+gThlQ2bSrFDlHOlhjhtSXgX/nzE3F7cdtnMdKjUg4+LCJEaxRAiC+jijqYBkGL,iv:EQzCHK+gla5TqK1dNbxfnUg+DgFc5tC/p5K3BwH6zSM=,tag:BrK22GeyUIGEtWSuLZ0wCw==,type:str]
    #ENC[AES256_GCM,data:e0O2c5othswurE1mEYNqk1FplRramrGisG43Ca9KVKLGnYlDipCxzdfQ0u96vpDCjBQfybfi,iv:RYP0gQZxWkCWP2SuGCVnU+ML21h5pnlknEae/M3Ank4=,tag:BVRz4knG6ub5mqRMxAnl3A==,type:comment]
    COUCHDB_PASSPHRASE: ENC[AES256_GCM,data:43YMxxcftXs+acLiWSBoroU/UHqhXf9+L5poMJAtqwQ=,iv:Wv+GhbrWVzAw+BTGCtb/B7SRqyCJc9/xQlNGlC93CC4=,tag:cmq6xPBv5K38T5wNAB4/JA==,type:str]
    #ENC[AES256_GCM,data:nMRgpb6AJZDTdCcdi49y3v7KabXJ,iv:9iYN3gR774Lj2d2eA2nM9pawqopGoTjqUxdUwAP8ozU=,tag:dTkr4oQgyQ9duvxJT2eXRQ==,type:comment]
    MCP_AUTH_TOKEN: ENC[AES256_GCM,data:TbPGsg7VLQDf3GuFYUZbaajakRvAcK9I2rbkox7j1a/l4X6fO1pu2m+Yi5RGL6pFubsViVlvs3YTIdN0/AAYIw==,iv:w+5V3IZm89xfrMFyDNyzLdpGHGMZw5PD1il6W6BoLg8=,tag:Ccb/5R46ywRIv4doYC6Rrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQemlMWlhqS2IwUEUvK09S
            UDZ3dTU0M1pKUHJidTlNZFRjVzh4WkJwKzBrClVjbGJrUzNpY0lhZ3Y5SlNGeVVL
            NVZFeWdDRHJ4WDUzRlMvK3puODF6TkUKLS0tIEZGcXJsN1ZZcklJbk9zcmR5YnB3
            SUNvajd0ZkNNUHVLRGxNTjBpUGkzYXMKR6NMVD7XuagfpzMdxnSZF6HuTOES6kec
            eCcQsnzCKJVwdK0lsLpgyJp/LTrt9urOLCqLvXJpt5UdEpqIVdlCPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFBXUDg4RkNIT3RMOGo1
            dHJJNzNBdm1NR294ZVVpQ3k2czMwa3QrZWtZCmluVGdtNExTSzE4akkrUFpscUQ2
            MW9SMGVzamxvTktaWUJFSGpxMk9ZWjgKLS0tIHU1RkJkc3hPVVRucE1BS2NrRk5v
            ejVIMndzVXQxeXArd0tmRWZVeDUyT1UKxA5xYHorfQSORp2VEO56H6s7SxwQhTkl
            LXx7uH8oZtndUQBAiM03Mnyu8TEB6tjEnYt/WK4yDfAU2jeS18PjaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T21:53:50Z"
    mac: ENC[AES256_GCM,data:uieFXy6fHjfRHtefJpHwWU/biNjBBC0o4BuUExAl69HJHjRO+0l2kCg/DqYuNnwUOKx8P2LtXiScnu/SLmTizSi89M+1slrWmiIE0a6WRTwBG5Us+kC53RZaP5GGgwauR7K3HPUijx7cW7LRowBgCOAPAP/8jwIyMnO6JkMUG24=,iv:sfgzV8b3tOxlA0lk0yNOKde7jnhEaiFfRoHBl9Eew0w=,tag:cahLU72CKUPjW0UPxDEebw==,type:str]
    version: 3.13.3
