apiVersion: v1
kind: Secret
metadata:
    name: homarr-secrets
    namespace: homarr
stringData:
    #ENC[AES256_GCM,data:LXC3A+pLsTuFcgoPt62WuyP5oeh22i/HRYTULPwxoTQKO3SwjcX9Z8UDJD8dcEM8W1hN5kU/gQwqBpTdbmqe5a4=,iv:+WFhRvq4LtwmvaYncXpUnO9/KccxIJ+J15lGIcEvfVA=,tag:s5R9MgPofPRSaL5UdIAHMA==,type:comment]
    #ENC[AES256_GCM,data:96DX/t7W1wJSAZE7GxUfrftSSiR80K0=,iv:tIwjbJ8ltQIG+IOn2NEzqD0Dwf6PM5WrLS+eB8RE4LY=,tag:wF6EnCTyyPPD9q6S9Qq74w==,type:comment]
    db-encryption-key: ENC[AES256_GCM,data:vGopOdHykn7tQ5mErhh9A2m4qw8uDmFycdb7QEiiwu+3UbIiNmIqEo2lBIg0FMh2ulFWcFMjT5GZHhYQQ8dqWw==,iv:y5O49j3DYpqmGvjxBixOZbzaWOxEfEDtUVxOxJYGh/U=,tag:NDrGRiv4BzA+9kR0fBrcxg==,type:str]
    #ENC[AES256_GCM,data:Nllbn/AnvBSZorx4R8TvI2JwPToy78MOJP/8RgFQazULUzKMQN0DhS+pBVfR9lmtFBoOySuz5dNyw8DImA9UzSYTP78M6U1rwvUZpR9O,iv:RVwg3rev6FUGiebxzw9uugDdC/WvT42evgPD546UEjk=,tag:4zFKG56069otDbBB4VHFoQ==,type:comment]
    #ENC[AES256_GCM,data:JNufCKAViudlLvyeu1nIlLbV3C7EprACUryI2eYWHallweZfcaVVToe+nK7SEw499Vmd5WhKYksWakB2PRxP6da3iGTuyynIjG2S7w==,iv:c2/N5TLf5mJFP3IQDLXgypogniA4+eoYAuGGQegfydw=,tag:WmoQyqDnhd+pKXn7ek62Qw==,type:comment]
    api-key: ENC[AES256_GCM,data:zsfW7fn6DjdwfRI9pxJ/jmbeICHjnAOpn0A7kYQSQH0DOMzXhJrlJWg=,iv:AjdNsMvCjIYmPrUDCmyqxPBGFtrGVR+5xOr2BP08bGg=,tag:gb4KEeSmDet3grWHNIcrMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eXFVdkN5U1E1M1lUTTJp
            YUozb1JpNk1pcHFnS0pEd1RJNmtkZTZhUVI0CkY5MUdOY0ZDUFkxYStkT1dMYkND
            dzk3bW9Od0ZWUE5UUmJsVzZSU1Vma00KLS0tIHlVNkVYenlTRm5sLzExRFRMemcx
            OGFFTzlpSmNFS2k4V0F6cTlEVVg4Q1kKlQXnr2IGjm4nstJKF0I3YI4igzqWi9oN
            bjsN7xt1FcSmM2ifbXfCdVFM08NwD8bOJy4vZ14Jrs3LgftsN0PmOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWEdiRC95S0d3ZjF6WTVK
            NDdWckFqZWxrN2dhT3RGaktQaDNrK0Zqc0ZFCmNybGp6M0srSDRoQjV4N0NoNHEw
            ZmhaTU5tVU8xbHZyaDF0K0ZhSitlV28KLS0tIGNqRXlEQmJVT29ZWGZPdldRb1c5
            RE4xdlZCNGU3bXQxQ0diMTM3V0x0ZWcKjhcOusRoMgifFWDN36txCrqSJdUoOzF1
            bpTDMDOjMBBLKvbIFSXzyjRdJd1gTZ1hVZgo0sW8sxHEJbwJ5XSH8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T13:12:06Z"
    mac: ENC[AES256_GCM,data:gzuBaXznAcFUgcpUKdBniXm6IHmXf4UjkX1D7qibSBwGQeakqW54ngsrRXX/wIqbsJUZXIOwAyh9iZz6RAIHX5ySrRJtL8CnQjvG9+F5pmJZnfiZbSwq+6JRXtVSZ8dvE4gT5kdtuJLotkHFEadNLLcXTpQFhNctBiAg9Wow3yU=,iv:StEAHHxhMBSrRBqPfVJn1FTPdqf/30VH41FEAJRxg3U=,tag:D4H5xgtRNcNQxYA1ztyejg==,type:str]
    version: 3.13.3
