apiVersion: v1
kind: ServiceAccount
metadata:
  name: homarr-httproute-sync
  namespace: homarr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homarr-httproute-sync
rules:
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homarr-httproute-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homarr-httproute-sync
subjects:
- kind: ServiceAccount
  name: homarr-httproute-sync
  namespace: homarr
