apiVersion: v1
kind: Secret
metadata:
  name: atlantis-github-secret
  namespace: atlantis
stringData:
  github-user: REPLACE_WITH_GITHUB_USERNAME
  github-token: REPLACE_WITH_GITHUB_TOKEN
  github-secret: REPLACE_WITH_WEBHOOK_SECRET
