apiVersion: v1
kind: Secret
metadata:
    name: slack-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:FbkGiRPResqnEHcy44mGDcz8WsYi2N6vVafAEhLmCcVV75I6u29VdeHlIQGT/L/xR6eMiMiTlE3hnlCixlpXwhxgfcZ7hbGtDJXAYyyd3D0D,iv:ICbCNR4OgPruOClzmJWyFhtDVHbKYWL/K20Qe2dhbOM=,tag:FRDrGHaplP1SGiqMBYeReQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbThlVlp6bC9oOFBDUlVU
            RmhNSGdrVDh4OUpIUVpaMDNIYlJNazEvSkdnCmFaMktDdkdHU1A3U1BzejJ4OWsy
            MTFrVFFBUTN0WmlhZkpkU2dVQkZmMU0KLS0tIHpLbWg2ZTNZVHdSSko1eVZOMm9n
            ald4clRvL2hrUFVIV2phQ1I3ODV1RzgKtwF2x3UKmULdjhJwJOoGNinLpftNew6/
            tak1hikutI+vg/v/wFIzscGJPsU4T/Lj+aiGauN/RkMqG5LXrSS5Ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UE52azBDYjdOeldFVUZs
            UDVyblVyMEN1by9QaGpBMllxaVYvM1QwT25zCm5CNmN6OWxjNlptTkxFMkNPeldm
            bUxodkk1T0JqY2V6VHM0VytMNXQ3MWcKLS0tIGVPRm1INkIvYTlKS1JHclpHOEpF
            SzJMZWhHbmxWZm5peUt1b1AzalFCRkEKw4MWYXhP4xQbR7nsFGVl4GFsY1lyX8r8
            N4c6b1Z9LeVFF8zNYA9FKRWNnleObmcrAYUIzLC/1Z3j1q6+gASFvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1470xftejp68uy54dn9vxwhnyuhgvpmf533nmn3mfya7uz558u3ls6v0r79
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-10T01:06:29Z"
    mac: ENC[AES256_GCM,data:+jYmYLA+47tzGtkhh3Tcxu8QE9xwUcMNa49MAAj2DlhVhHcJtC1SBQUbv5eZPMDOisnBGhMssKgj69EWIOr0RzdJV3zE0lMJoXBLGKIJ1V1ERDbZvDxv8RfnNOCi7k8B3G4xf45EVLH198r+QXjeLA6gfjHhHWKpQdSORaONE+k=,iv:JSF+Ery07BnaDkNGKZb2JbGcx/lgLA7JtqM/YZoDL1w=,tag:/jMhiIeREMTBJP5KK8D6OQ==,type:str]
    version: 3.11.0
