apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-url
  namespace: flux-system
stringData:
  address: ENC[AES256_GCM,data:FbkGiRPResqnEHcy44mGDcz8WsYi2N6vVafAEhLmCcVV75I6u29VdeHlIQGT/L/xR6eMiMiTlE3hnlCixlpXwhxgfcZ7hbGtDJXAYyyd3D0D,iv:ICbCNR4OgPruOClzmJWyFhtDVHbKYWL/K20Qe2dhbOM=,tag:FRDrGHaplP1SGiqMBYeReQ==,type:str]
sops:
  age:
  - recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZXB1UUVickUrV3dlZ0lD
      bFhXNWk5Y2hFWlU2V1JVaFYwRDBiQkVTQm1jCkRYT2JhcUNkTEF6UGE0akJkdE4w
      YW4yUzE0WGlkTkMzT2ZFWjVoN1NOYlUKLS0tIFlxWHZUWU52cjNrVkpzYW82Wm5t
      QkVzNSs1cGNPS3g1c3JXTFdJNm9RaTQKXeWVx+AfbOqq+zoTbpzHFJ27PJJ2Ph8A
      lM8GRfDylyRJKVsanrYhSfd2QG/p2TLnNEcL/M4rEQBQ6ZbZ7XEjWg==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T01:06:29Z"
  mac: ENC[AES256_GCM,data:+jYmYLA+47tzGtkhh3Tcxu8QE9xwUcMNa49MAAj2DlhVhHcJtC1SBQUbv5eZPMDOisnBGhMssKgj69EWIOr0RzdJV3zE0lMJoXBLGKIJ1V1ERDbZvDxv8RfnNOCi7k8B3G4xf45EVLH198r+QXjeLA6gfjHhHWKpQdSORaONE+k=,iv:JSF+Ery07BnaDkNGKZb2JbGcx/lgLA7JtqM/YZoDL1w=,tag:/jMhiIeREMTBJP5KK8D6OQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
