name: Kubernetes Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'kubernetes/components/**'
  push:
    branches:
      - main
    paths:
      - 'kubernetes/components/**'

jobs:
  validate:
    uses: hazim1093/ci/.github/workflows/k8s-validation.yml@main
    with:
      roots: kubernetes/components
