apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
# Create a Cloudflare API Token with Zone:DNS:Edit and Zone:Zone:Read permissions
# https://dash.cloudflare.com/profile/api-tokens
stringData:
  api-token: ENC[AES256_GCM,data:4TlDJXNHkfE3ZrC3DsNwY2M6ERfCeQjRR1RCnOJaH/OPthHGAtHGpw==,iv:p9pZIIaFfF3ZxmXnsYkxBw4RCUfq6iE7p/tIZIDd1DM=,tag:CKSdYMLdGXQl/xuI2w/maw==,type:str]
sops:
  age:
  - recipient: age1s84t0ws8cpp8ujf8mny373gg63g9d52fezrdwe24jdfe4d309pwqvawpcu
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TlUxUXd0d2IxVFhCallK
      NnhtcXFTRjhVdjgxeHlDNU9vVGxJZmhhdmo4CkUxbjgwZWN5S1NmVGp3ZWpqSDNq
      OTFFb3YzVlFFK0p0MS9jYXArQ2R0cFUKLS0tIDZONEJaMUZWUVBYbE5sRnM5c0s5
      RWZhVGpXVng0LzBwc2h2WjJwVlo0MmsKpSvfTca5Texl4gokJL6PfUpBUJi4xepE
      5xpsP6F0TP3j3h0Udqogwvp3CckqKdh9MFLAqCeAkgkKpod2jDrz0A==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T01:15:59Z"
  mac: ENC[AES256_GCM,data:VYR1Etna+MXABI7qa653iBQy0hAusD159QWAIdexmpC8bWqUX+LcnGisYKLY1Jp6RQKwltxZ7xZjY0wVgZhv4oKeJDy1xpKGm9JCFrmaKTYEzOJggKu7e5VmiQ250giQZw4aaOl3U9Gqw/7UfoethrS1oUuf9CVPMbmuIO9jLd4=,iv:MFD3ezsxdKvtwq2DuLE6GPxOM/VfdC+FP1qQeWCoDB8=,tag:GVpuf7VsjhX8PrGsycnD+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
